### ISSUE TITLE
Simplify container naming and DOCKER_RUN -- or remove it?

### ISSUE THREAD

**Issue by joestubbs** [waltermoreira/serfnode#3]
Right now there is some complexity in using serfnode with the "DOCKER_RUN" environmental variable. You have to name the sernode container and then pass the "--net container <serfonode_name" string in. Seems like this is overly complex and could be completely hidden from the end user.

Additionally, the DOCKER_NAME variable could lead to confusion when combined with the DOCKER_RUN, since you could add a name to the container through the DOCKER_RUN string.

With this in mind, perhaps it is better to just deprecate the environmental variable API and promote the "config file API" instead. I think the config file may makes things simpler in a number of ways.

**Comment by waltermoreira** [comment]
The "--net container" is handled by serfnode.  We don't need to pass that option.  I also like  more the serfnode.yml and serfnode.py vs. the environment variable.  Agree with deprecating it.

**Comment by waltermoreira** [comment]
New API supports only serfnode.yml as a way of spawning children. Closing this issue.

**Comment by deardooley** [comment]
If it's ok, I'd like to fork and use the environment variables because if the yaml is going to support a bit more of the CLI, then it makes configuring the children statically a bit easier. For instance, mapping hosts to alternative hostnames hard coded into existing projects. Also, many images do not run as trusted users, so they may not/should not have access to the underlying discovery API.
